### ISSUE TITLE
Minor errors

### ISSUE THREAD

**Issue by AbergDevcore** [nicolaayan/EpiserverCmsAudit#1]
Nothing showing in site audit when there is only one site and console error of null when auditing blocks. In _layout on row 144 the conditional expression checks for "$tabs.length > 1" while it should be 0, and on row 183 the selector $('#tbl-content-types tr') in cludes the table header row, causing a console error. Concider using selector $('#tbl-content-types tbody tr')

**Comment by nicolaayan** [comment]
This has been in Allan's v2 version of the package - #5
