### ISSUE TITLE
If star (*) is missing in hostnames and content has a language which is not set up or deleted the list failes

### ISSUE THREAD

**Issue by oyvindwh** [nicolaayan/EpiserverCmsAudit#13]
In the function GetContentItemsOfTypes this line will fail if the * is missing in hostnames and the content can not get the current sitedefinition. 

`_siteDefinitionResolver.GetByContent(cmu, true)**.id ** will throw an exception.`

Perhaps update the documentation or have a fallback guid if GetByContent returns null?

**Comment by nicolaayan** [comment]
Hi @oyvindwh 
I've recently fixed this in v1.4.1. It was failing for pages that didn't belong to any Site Definition (i.e. floating pages) as you've pointed out. Have added a fallback empty GUID for those.
Thanks
