### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by oyvindwh** [nicolaayan/EpiserverCmsAudit#2]
I get a 404 error for all block types in the console and Usages shows 0 site(s), 0 block(s).  Pagetypes works fine. See the attached image. This is a solution with 2 sites. 

![2018-07-27_13-26-13](https://user-images.githubusercontent.com/106393/43318406-f33e2b90-91a0-11e8-8b56-6fbf48643004.png)
![2018-07-27_13-26-29](https://user-images.githubusercontent.com/106393/43318407-f357f1d8-91a0-11e8-847e-24bd09e1776d.png)

**Comment by stibay** [comment]
The problem is that episerver might not be mapped to /episerver so either change that to what yours is running under or change to relative paths instead of absolute path in _layout.cshtml.

F.ex instead of url: '/episerver/cmsaudit/cmsaudit/indexsiteaudit', to just url: 'indexsiteaudit',
