### ISSUE TITLE
Specific pages give NullReferenceException

### ISSUE THREAD

**Issue by MadsGosvig** [nicolaayan/EpiserverCmsAudit#6]
We have a few pages (3) which gives a NullReferenceException when viewing the PageTypeAudit.
It is the following pages:

- Login Page
- SysRoot
- SysRecycleBin

Our PageTree looks like this:
![image](https://user-images.githubusercontent.com/20351513/48046715-b81bb380-e195-11e8-8ac0-353bead318d1.png)

And this is the error that we are getting:
![image](https://user-images.githubusercontent.com/20351513/48046732-c4a00c00-e195-11e8-835b-660088efd3f4.png)

I just spend 1-2 minutes debugging - But it seems that this is the part of the code which throws the error:
![image](https://user-images.githubusercontent.com/20351513/48046775-f44f1400-e195-11e8-8c86-cba5625a6886.png)

We are currently using version 1.2.0

**Comment by nicolaayan** [comment]
Hi @MadsGosvig,
I've recently fixed this in v1.4.1. It was failing for pages that didn't belong to any Site Definition (i.e. floating pages).
Thanks
